# PyTorch Intro 


## Tensors
- similar to NumPy's ndarrays
- addition: Tensors can also be used on a GPU to accelerate computing

In [1]:
from __future__ import print_function
import torch

In [7]:
# construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.3810, 0.1070, 0.4169],
        [0.9315, 0.7817, 0.1539],
        [0.1158, 0.6278, 0.1971],
        [0.0122, 0.1993, 0.0056],
        [0.3942, 0.4452, 0.0227]])


In [8]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6217,  1.3974, -0.7609],
        [ 0.1569, -2.0034,  0.0420],
        [-0.9395, -1.5434, -1.6380],
        [ 0.3324,  0.2554, -1.4671],
        [ 0.1105, -0.7182,  0.1140]])


In [10]:
# get tensor size --> tuple
print(x.size())

torch.Size([5, 3])


### Operations

In [11]:
# syntax 1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.5116,  2.2507, -0.5364],
        [ 1.1517, -1.7190,  0.6366],
        [-0.6623, -1.0800, -1.4911],
        [ 0.5671,  0.9088, -1.0446],
        [ 0.5916, -0.2629,  0.7154]])


In [ ]:
# syntax 2
print(torch.add(x, y))

In [ ]:
# in place
y.add_(x)
print(y)

In [ ]:
# You can use standard NumPy-like indexing 
print(x[:, 1])

In [ ]:
# Resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

In [12]:
# If you have a one element tensor, 
# use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0247])
1.0247364044189453


More operations: https://pytorch.org/docs/stable/torch.html

### NumPy Bridge
- Easy to convert Torch Tensor to a NumPy array

In [15]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convert NumPy array to Torch Tensor

In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [19]:
%time
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

CPU times: user 5 µs, sys: 1 µs, total: 6 µs
Wall time: 11.9 µs
tensor([2.0247], device='cuda:0')
tensor([2.0247], dtype=torch.float64)


# Resources
- https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py