# PyTorch Intro 


## autograd package
- central to all neural networks in PyTorch
- provides automatic differentiation for all operations on Tensors
- define-by-run framework, meaning that your backprop is defined by how your code is run, and that every single iteration can be different

### Tensor
- `torch.Tensor` is the central class of the package
- setting `.requires_grad` as `True` tracks all operations on it
- call `.backward()` and have all the gradients computed automatically
 - gradient for this tensor will be accumulated into `.grad attribute

- `Function` and `Tensor` are interconnected and build up an acyclic graph that encodes a complete history of computation
 - Each tensor has a `.grad_fn` attribute that references a Function that has created the Tensor

In [2]:
from __future__ import print_function
import torch

Create a tensor and set requires_grad=True to track computation with it

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
# do an operation
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
# y was created as a result of an operation, so it has a grad_fn.
print(y.grad_fn)

In [6]:
# do more operations on y
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
print(a.grad_fn)
b = (a * a).sum()
print(b.grad_fn)

False
True
None


### Gradients
Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.)).

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
out.backward()

In [11]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# Resources
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html